# Generated by Django 4.0.3 on 2022-03-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_place_delete_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',), 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
    ]
