# Generated by Django 4.0.3 on 2022-03-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_wishlistandvisitedplace_visited_places_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistandvisitedplace',
            options={'verbose_name': 'Wishlist and Visited Place', 'verbose_name_plural': 'Wishlist and Visited Places'},
        ),
        migrations.AlterField(
            model_name='wishlistandvisitedplace',
            name='visited_places',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='wishlistandvisitedplace',
            name='wishlist',
            field=models.TextField(default='[]'),
        ),
        migrations.CreateModel(
            name='OurRecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.place')),
            ],
            options={
                'verbose_name': 'Our Recommendation',
                'verbose_name_plural': 'Our Recommendations',
            },
        ),
    ]
