# Generated by Django 4.0.3 on 2022-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
