# Generated by Django 4.0.3 on 2022-03-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_wishlistandvisitedplace_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistandvisitedplace',
            name='wishlist',
            field=models.TextField(default='[]'),
        ),
    ]
