# Generated by Django 4.0.3 on 2022-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_wishlistandvisitedplace_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.URLField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
